version: "3"

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 95941412
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
